app:
  build: .
  dockerfile: Dockerfile-dev
  volumes:
    - .:/umbrella
  ports:
    - 4000:4000

web:
  extends: app
  environment:
    - USER
    - USERNAME
    - MIX_ENV=dev
    - PG_USERNAME=postgres
    - PG_PASSWORD=postgres
    - PG_HOST=db
  links:
    - db

tests:
  extends: app
  command: mix do coveralls, credo --strict
  environment:
    - USER
    - USERNAME
    - MIX_ENV=test
    - PG_USERNAME=postgres
    - PG_PASSWORD=postgres
    - PG_HOST=db
  links:
    - db

db:
  image: postgres:11.5
  environment:
    - POSTGRES_PASSWORD=postgres
  ports:
    - 5432
